project_id = "aubastwqendcpwwbusgs"

[functions.ai-study]
verify_jwt = false

[functions.extract-pdf-text]
verify_jwt = false

[functions.extract-pdf-text-ocr]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.job-search]
verify_jwt = false
