import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Switch } from '@/components/ui/switch';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Users, Plus, MessageSquare, Trash2, UserPlus, ArrowRight, Lock, Globe, Key, Copy, Check } from 'lucide-react';

interface StudyGroup {
  id: string;
  name: string;
  description: string | null;
  topic: string | null;
  creator_id: string;
  is_public: boolean;
  max_members: number;
  invitation_code?: string;
  member_count?: number;
  is_member?: boolean;
}

const StudyGroups = () => {
  const { user } = useAuth();
  const { toast } = useToast();
  const navigate = useNavigate();
  const [groupName, setGroupName] = useState('');
  const [topic, setTopic] = useState('');
  const [isPublic, setIsPublic] = useState(true);
  const [creating, setCreating] = useState(false);
  const [groups, setGroups] = useState<StudyGroup[]>([]);
  const [loading, setLoading] = useState(true);
  const [joinCode, setJoinCode] = useState('');
  const [joining, setJoining] = useState(false);
  const [showJoinDialog, setShowJoinDialog] = useState(false);
  const [copiedCode, setCopiedCode] = useState<string | null>(null);
  const [newGroupCode, setNewGroupCode] = useState<string | null>(null);

  useEffect(() => {
    if (user) {
      fetchGroups();
    }
  }, [user]);

  const fetchGroups = async () => {
    try {
      // Fetch groups user is member of
      const { data: memberGroups } = await supabase
        .from('study_group_members')
        .select('group_id')
        .eq('user_id', user?.id);

      const memberGroupIds = new Set(memberGroups?.map(m => m.group_id) || []);

      // Fetch public groups and groups user is member of
      const { data: groupsData, error: groupsError } = await supabase
        .from('study_groups')
        .select('*')
        .order('created_at', { ascending: false });

      if (groupsError) throw groupsError;

      // Filter: public groups OR groups user is member of
      const visibleGroups = (groupsData || []).filter(g => 
        g.is_public || memberGroupIds.has(g.id)
      );

      // Fetch member counts
      const groupsWithData = await Promise.all(visibleGroups.map(async (group) => {
        const { count } = await supabase
          .from('study_group_members')
          .select('*', { count: 'exact', head: true })
          .eq('group_id', group.id);

        return {
          ...group,
          member_count: count || 0,
          is_member: memberGroupIds.has(group.id),
        };
      }));

      setGroups(groupsWithData);
    } catch (error) {
      console.error('Error fetching groups:', error);
    } finally {
      setLoading(false);
    }
  };

  const createGroup = async () => {
    if (!groupName.trim() || !user) {
      toast({ title: 'Enter a group name', variant: 'destructive' });
      return;
    }

    setCreating(true);
    try {
      // Note: invitation_code is auto-generated by a database trigger
      const { data: newGroup, error } = await supabase
        .from('study_groups')
        .insert([{
          name: groupName.trim(),
          topic: topic.trim() || null,
          creator_id: user.id,
          is_public: isPublic,
        }] as any)
        .select()
        .single();

      if (error) throw error;

      // Add creator as member
      await supabase
        .from('study_group_members')
        .insert({
          group_id: newGroup.id,
          user_id: user.id,
          role: 'admin',
        });

      if (!isPublic) {
        setNewGroupCode(newGroup.invitation_code);
      }

      toast({
        title: 'Study Group Created!',
        description: isPublic 
          ? `"${groupName}" is ready. Invite friends to join!`
          : `Private group created. Share the invite code with friends.`,
      });
      
      setGroupName('');
      setTopic('');
      setIsPublic(true);
      fetchGroups();
    } catch (error) {
      console.error('Error creating group:', error);
      toast({ title: 'Failed to create group', variant: 'destructive' });
    } finally {
      setCreating(false);
    }
  };

  const joinByCode = async () => {
    if (!joinCode.trim() || !user) return;

    setJoining(true);
    try {
      // Find group by invitation code
      const { data: group, error: findError } = await supabase
        .from('study_groups')
        .select('id, name')
        .eq('invitation_code', joinCode.trim().toUpperCase())
        .single();

      if (findError || !group) {
        toast({ title: 'Invalid invite code', variant: 'destructive' });
        setJoining(false);
        return;
      }

      // Check if already a member
      const { data: existing } = await supabase
        .from('study_group_members')
        .select('id')
        .eq('group_id', group.id)
        .eq('user_id', user.id)
        .maybeSingle();

      if (existing) {
        toast({ title: 'Already a member of this group' });
        setShowJoinDialog(false);
        setJoinCode('');
        navigate(`/group/${group.id}`);
        return;
      }

      // Join the group
      const { error } = await supabase
        .from('study_group_members')
        .insert({
          group_id: group.id,
          user_id: user.id,
          role: 'member',
        });

      if (error) throw error;

      toast({ title: `Joined ${group.name}!` });
      setShowJoinDialog(false);
      setJoinCode('');
      fetchGroups();
      navigate(`/group/${group.id}`);
    } catch (error) {
      console.error('Error joining group:', error);
      toast({ title: 'Failed to join group', variant: 'destructive' });
    } finally {
      setJoining(false);
    }
  };

  const joinGroup = async (groupId: string) => {
    if (!user) return;

    try {
      const { error } = await supabase
        .from('study_group_members')
        .insert({
          group_id: groupId,
          user_id: user.id,
          role: 'member',
        });

      if (error) throw error;

      toast({ title: 'Joined group!' });
      fetchGroups();
    } catch (error) {
      console.error('Error joining group:', error);
      toast({ title: 'Failed to join group', variant: 'destructive' });
    }
  };

  const leaveGroup = async (groupId: string) => {
    if (!user) return;

    try {
      const { error } = await supabase
        .from('study_group_members')
        .delete()
        .eq('group_id', groupId)
        .eq('user_id', user.id);

      if (error) throw error;

      toast({ title: 'Left group' });
      fetchGroups();
    } catch (error) {
      console.error('Error leaving group:', error);
      toast({ title: 'Failed to leave group', variant: 'destructive' });
    }
  };

  const deleteGroup = async (groupId: string) => {
    if (!user) return;

    try {
      const { error } = await supabase
        .from('study_groups')
        .delete()
        .eq('id', groupId)
        .eq('creator_id', user.id);

      if (error) throw error;

      toast({ title: 'Group deleted' });
      fetchGroups();
    } catch (error) {
      console.error('Error deleting group:', error);
      toast({ title: 'Failed to delete group', variant: 'destructive' });
    }
  };

  const copyCode = async (code: string) => {
    await navigator.clipboard.writeText(code);
    setCopiedCode(code);
    toast({ title: 'Invite code copied!' });
    setTimeout(() => setCopiedCode(null), 2000);
  };

  if (loading) {
    return (
      <div className="space-y-2">
        {[...Array(3)].map((_, i) => (
          <div key={i} className="h-20 rounded-xl bg-muted animate-pulse" />
        ))}
      </div>
    );
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-6"
    >
      {/* Create Group */}
      <Card className="p-6 bg-card border-border">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center">
            <Plus className="w-5 h-5 text-primary" />
          </div>
          <h3 className="font-semibold text-foreground">Create Study Group</h3>
        </div>

        <div className="space-y-3">
          <Input
            placeholder="Group name..."
            value={groupName}
            onChange={(e) => setGroupName(e.target.value)}
          />
          <Input
            placeholder="Study topic (optional)"
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
          />
          
          <div className="flex items-center justify-between p-3 rounded-lg bg-muted/50">
            <div className="flex items-center gap-2">
              {isPublic ? <Globe className="w-4 h-4 text-primary" /> : <Lock className="w-4 h-4 text-yellow-500" />}
              <Label htmlFor="public-switch" className="text-sm">
                {isPublic ? 'Public group' : 'Private (invite only)'}
              </Label>
            </div>
            <Switch
              id="public-switch"
              checked={isPublic}
              onCheckedChange={setIsPublic}
            />
          </div>

          <Button
            onClick={createGroup}
            disabled={creating || !groupName.trim()}
            className="w-full gradient-primary text-primary-foreground"
          >
            {creating ? (
              <div className="w-5 h-5 border-2 border-primary-foreground border-t-transparent rounded-full animate-spin" />
            ) : (
              <>
                <Plus className="w-4 h-4 mr-2" />
                Create Group
              </>
            )}
          </Button>
        </div>
      </Card>

      {/* Join by Code */}
      <Card className="p-4 bg-card border-border">
        <Button
          variant="outline"
          className="w-full"
          onClick={() => setShowJoinDialog(true)}
        >
          <Key className="w-4 h-4 mr-2" />
          Join with Invite Code
        </Button>
      </Card>

      {/* Groups List */}
      <div>
        <h3 className="font-semibold text-foreground mb-3 flex items-center gap-2">
          <Users className="w-5 h-5 text-primary" />
          Study Groups ({groups.length})
        </h3>

        {groups.length === 0 ? (
          <Card className="p-8 bg-card border-border text-center">
            <MessageSquare className="w-12 h-12 mx-auto text-muted-foreground mb-3" />
            <p className="text-muted-foreground">No study groups yet</p>
            <p className="text-sm text-muted-foreground">Create the first one!</p>
          </Card>
        ) : (
          <div className="space-y-3">
            {groups.map((group) => (
              <motion.div
                key={group.id}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
              >
                <Card className="p-4 bg-card border-border hover:border-primary/50 transition-colors">
                  <div className="flex items-center justify-between">
                    <div 
                      className="flex-1 cursor-pointer"
                      onClick={() => group.is_member && navigate(`/group/${group.id}`)}
                    >
                      <div className="flex items-center gap-2">
                        {!group.is_public && <Lock className="w-3 h-3 text-yellow-500" />}
                        <h4 className="font-medium text-foreground">{group.name}</h4>
                        {group.is_member && (
                          <span className="px-2 py-0.5 bg-primary/20 text-primary text-xs rounded-full">
                            Joined
                          </span>
                        )}
                      </div>
                      <div className="flex items-center gap-3 mt-1 text-sm text-muted-foreground">
                        <span className="flex items-center gap-1">
                          <Users className="w-3 h-3" />
                          {group.member_count}/{group.max_members}
                        </span>
                        {group.topic && (
                          <span className="truncate max-w-[150px]">{group.topic}</span>
                        )}
                      </div>
                    </div>
                    <div className="flex gap-2">
                      {group.is_member && (
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => navigate(`/group/${group.id}`)}
                        >
                          <ArrowRight className="w-4 h-4" />
                        </Button>
                      )}
                      {group.creator_id === user?.id ? (
                        <>
                          {group.invitation_code && (
                            <Button
                              size="sm"
                              variant="ghost"
                              onClick={() => copyCode(group.invitation_code!)}
                            >
                              {copiedCode === group.invitation_code ? (
                                <Check className="w-4 h-4 text-green-500" />
                              ) : (
                                <Copy className="w-4 h-4" />
                              )}
                            </Button>
                          )}
                          <Button
                            size="sm"
                            variant="ghost"
                            className="text-destructive hover:text-destructive"
                            onClick={(e) => { e.stopPropagation(); deleteGroup(group.id); }}
                          >
                            <Trash2 className="w-4 h-4" />
                          </Button>
                        </>
                      ) : group.is_member ? (
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={(e) => { e.stopPropagation(); leaveGroup(group.id); }}
                        >
                          Leave
                        </Button>
                      ) : (
                        <Button
                          size="sm"
                          onClick={() => joinGroup(group.id)}
                          disabled={(group.member_count || 0) >= group.max_members}
                        >
                          <UserPlus className="w-4 h-4 mr-1" />
                          Join
                        </Button>
                      )}
                    </div>
                  </div>
                </Card>
              </motion.div>
            ))}
          </div>
        )}
      </div>

      {/* Join by Code Dialog */}
      <Dialog open={showJoinDialog} onOpenChange={setShowJoinDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Key className="w-5 h-5" />
              Join with Invite Code
            </DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <Input
              placeholder="Enter invite code (e.g., ABC12345)"
              value={joinCode}
              onChange={(e) => setJoinCode(e.target.value.toUpperCase())}
              className="font-mono text-center text-lg tracking-wider"
              maxLength={8}
            />
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowJoinDialog(false)}>
              Cancel
            </Button>
            <Button 
              onClick={joinByCode}
              disabled={joining || joinCode.length < 8}
            >
              {joining ? (
                <div className="w-4 h-4 border-2 border-primary-foreground border-t-transparent rounded-full animate-spin" />
              ) : (
                'Join Group'
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* New Group Code Dialog */}
      <Dialog open={!!newGroupCode} onOpenChange={() => setNewGroupCode(null)}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Lock className="w-5 h-5 text-yellow-500" />
              Private Group Created
            </DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-4 text-center">
            <p className="text-muted-foreground">Share this invite code with friends:</p>
            <div className="flex items-center justify-center gap-2">
              <code className="text-2xl font-mono font-bold tracking-wider bg-primary/10 px-4 py-2 rounded-lg">
                {newGroupCode}
              </code>
              <Button size="icon" variant="ghost" onClick={() => copyCode(newGroupCode!)}>
                {copiedCode === newGroupCode ? (
                  <Check className="w-5 h-5 text-green-500" />
                ) : (
                  <Copy className="w-5 h-5" />
                )}
              </Button>
            </div>
          </div>
          <DialogFooter>
            <Button onClick={() => setNewGroupCode(null)}>Done</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </motion.div>
  );
};

export default StudyGroups;
